[features]
seeds = false
skip-lint = false
[programs.localnet]
partner_nft = "EaWjKSxRQLL5EvzD1BXDDdcvM9rPRFnEJQxiZetnJkRo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/zer0/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
